# Makefile
CC=gcc
CFLAGS=-c -Wall

all: file_manipulation shape_manipulation

file_manipulation: file_manipulation.c
	$(CC) $(CFLAGS) file_manipulation.c -o file_manipulation.o

shape_manipulation: shape_manipulation.c
	$(CC) $(CFLAGS) shape_manipulation.c -o shape_manipulation.o
